### PR TITLE
Removing the "www."

### PR DESCRIPTION
**Pull request by itz-rj-here**

### CODE REVIEW

**Comment by ChristianKernDev** [comment]
What is the reason for this change?

**Comment by itz-rj-here** [comment]
It automatically removes the www. when running the link 
so it will be better to remove the extra words

**Comment by itz-rj-here** [comment]
It's your wish if you want the www. or remove the www.

**Comment by ChristianKernDev** [comment]
I disagree, for example the URL: https://www.fork.gg/data/screenshots/settings1.png is not resolved to https://fork.gg/data/screenshots/settings1.png
The "www." is not really needed, but widely established to be used for websites, as it indicates on a first look that this domain points to a website and will return something wenn called with a GET request on port 80 or 443

**Pull request closed without merging**
